package com.shark.feifei.query.cache.data;

import java.util.Objects;

/**
 * Key generated by {@link com.shark.feifei.query.query.Query}
 * @Author: Shark Chili
 * @Date: 2018/11/14 0014
 */
public class QueryKey {
	private String sql;

	public QueryKey(String sql) {
		this.sql = sql;
	}

	@Override
	public int hashCode() {
		return Objects.hashCode(sql);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof QueryKey){
			QueryKey otherQueryKey = (QueryKey) obj;
			// Both are converted to uppercase, and both Spaces are removed for comparison
			return this.sql.trim().toUpperCase().equals(otherQueryKey.sql.trim().toUpperCase());
		}
		return false;
	}

	/**
	 * Get string of the key
	 * @return a string
	 */
	public String idetify(){
		return "Sql-"+sql;
	}

	@Override
	public String toString() {
		return "QueryKey{" +
				"sql='" + sql + '\'' +
				'}';
	}
}
